### PR TITLE
Add libsparkcolourpicker and libsparkapplist

### PR DESCRIPTION
**Pull request by LillieWeeb001**
Hi Kirb, you asked me to pr these in.

### CODE REVIEW

**Review by PoomSmart — COMMENTED** [review]
I recommend formatting the headers (indentations, inter-spaces and so on) to be similar to the others.

**Comment by PoomSmart** [comment]
cc @SparkDev97

**Comment by kirb** [comment]
The code style is a bit out of the expected but not something we should really worry about. We shouldn't reformat code inherited from 3rd party projects - this should only apply to reversed headers.

**Review by kirb — CHANGES_REQUESTED** [review]
Could you please update LICENSE.md with info on the licenses of these projects?

**Comment by leptos-null** [comment]
I believe these headers should be in appropriately named directories, likely `libsparkcolourpicker` and `libsparkapplist`.

**Comment by SparkDev97** [comment]
> The code style is a bit out of the expected but not something we should really worry about. We shouldn't reformat code inherited from 3rd party projects - this should only apply to reversed headers.

Feel free to reformat the headers as you see fit. These were only ever intended to be private, so I never bothered to tidy them up. I only released these at a pinch when someone asked to use them.

**Comment by kirb** [comment]
Dealt with adding the license info to LICENSE.md and merged in with 1fed549. Thanks!

**Pull request closed without merging**
