### PR TITLE
Fix NSXPCConnection header compilation errors for some people

### PR DESCRIPTION
**Pull request by ArtikusHG**

### CODE REVIEW

**Comment by PoomSmart** [comment]
Can you resolve merge conflicts?

**Comment by PoomSmart** [comment]
Why some of the methods have to be removed?

**Comment by leptos-null** [comment]
I agree with PoomSmart. I think if all of Foundation is imported, this should compile.

**Comment by ArtikusHG** [comment]
"I think if all of Foundation is imported, this should compile" - apparently it doesn't. It errors "expected a type" for xpc_type_t in the definitions, even if xpc/xpc.h is included; I thought this was a rather good idea since a) noone really uses the methods and b) the error doesn't make *any* sense (the methods using xpc_type_t are inside an if statement and are only meant to be read by the compiler if xpc.h is included in the first place)

**Comment by leptos-null** [comment]
For some `SRC_FILE`:
```objc
#import <Foundation/NSXPCConnection.h>

int main() {
}
```

```sh
clang -I $THEOS/vendor/include -isysroot $(xcrun --sdk iphoneos --show-sdk-path) -arch arm64 SRC_FILE
```
exits withouts errors for me.

---

> the methods using xpc_type_t are inside an if statement and are only meant to be read by the compiler if xpc.h is included in the first place

this is not quite accurate. `__has_include` evaluates to true if
> its _operand_ can be included using the ‘#include’ directive

  - https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005finclude.html

Perhaps people that are having this error
- have `<xpc/xpc.h>` and are not including it, or 
- have `<xpc/xpc.h>`, are including it, but it does not have the type being used. 

Upon testing this further, if I have no `<xpc/xpc.h>`, this compiles without errors. 
If I have `<xpc/xpc.h>` of any kind, compilation fails because this header (`Foundation/NSXPCConnection.h`) does not include/import `<xpc/xpc.h>`. If I have a relatively reasonable `<xpc/xpc.h>`, and include `<xpc/xpc.h>` myself, this compiles without errors. 

My suggestion would be to add

```objc
#if __has_include(<xpc/xpc.h>)
#    import <xpc/xpc.h>
#endif
```
to the top of this file.

**Comment by kirb** [comment]
Since we’ve now merged #59, I think this shouldn’t be necessary any more. Thanks for contributing and sorry I took 6 months to deal with this PR…

**Pull request closed without merging**
