### PR TITLE
Remove common 3rd party headers and update code rules

### PR DESCRIPTION
**Pull request by L1ghtmann**
What does this implement/fix? Explain your changes.
---------------------------------------------------
- Removes openssl and libarchive headers
- Code rules updated to advise against including common 3rd party headers available from cross-platform dev packages

Checklist
---------
- [ ] New code follows the [code rules](https://github.com/theos/headers/blob/master/README.md#code-rules)
- [ ] I've added modulemaps for any new libraries (e.g. see [libactivator/module.modulemap](https://github.com/theos/headers/blob/f3e596d896bae8f07c43cfb00ef55bf6224b4cdc/libactivator/module.modulemap)): it should be possible to `@import MyLibrary;` in ObjC, or `import MyLibrary` in Swift.
- [ ] My contribution is code written by myself from reverse-engineered headers, licensed into the Public Domain as per [LICENSE.md](LICENSE.md); or, code written by myself / taken from an existing project, released under an OSI-approved license, and I've added relevant licensing credit to [LICENSE.md](LICENSE.md)

Does this close any currently open issues?
------------------------------------------
#73 

Any relevant logs, error output, etc?
-------------------------------------

Any other comments?
-------------------
- Potentially breaking change
- Headers are provided by respect `*-dev` packages on Linux and respective lib or `*-dev` packages on iOS.
  - Unsure about OSX

Where has this been tested?
---------------------------
**Operating System:** …

**Platform:** …

**Target Platform:** …

**Toolchain Version:** …

**SDK Version:** …

### CODE REVIEW

**Review by leptos-null — COMMENTED** [review]
I think this is great. I would like to verify that there are no major projects that use these headers.

I also think we should provide very clear instructions on how to switch to using the `*-lib` packages on each platform for developers that are impacted.

**Comment by leptos-null** [comment]
> where do you think [additional instructions] should be placed?

Maybe a wiki page on this repo.

I'm thinking this because it's for users (i.e. theos users) less than developers (i.e. theos contributors).

---

#### Draft

Theos no longer provides headers for some libraries that provide headers through their own releases. For example, OpenSSL provides its headers in the `openssl-dev` package. This more easily allows developers to use the headers matching their deployment target.

To use headers from these libraries with Theos, follow these steps:
1. Install the associated `dev` package on the device you're targeting (often this is your iOS device)
2. Copy the header files the package installs to `$THEOS/includes/`. Usually packages install the headers to `/usr/local/include/`. For example, the headers may be located at `/usr/local/include/openssl/`. Copy this to your Theos development environment at `$THEOS/include/openssl/`.

**Comment by L1ghtmann** [comment]
Ooo, hadn't thought of the wiki. Nice, thanks! Also, just to clarify, the headers don't need to be moved anywhere once installed since they're installed to a system include path.

**Comment by L1ghtmann** [comment]
New wiki page has been [created](https://github.com/theos/headers/wiki/Developer-Notes)! Guess the last item would be confirming the existing headers aren't widely used. Not sure how exactly to best approach verifying that, so ideas are welcome

**Comment by leptos-null** [comment]
Thanks for the wiki page!
I did a search on GitHub for https://github.com/search?q=THEOS++path%3A**%2FMakefile+archive&type=code and found only two projects.
- https://github.com/opa334/TrollStore
- https://github.com/L1ghtmann/IAmLazy

I'm comfortable moving forward with this.

**Review by leptos-null — APPROVED** [review]

**Comment by L1ghtmann** [comment]
Great, thanks for checking! I can modify my project in the next update and have posted a [pr to Trollstore](https://github.com/opa334/TrollStore/pull/672) with the necessary change.

**Comment by leptos-null** [comment]
Forgot to add the search for OpenSSL https://github.com/search?q=THEOS++path%3A**%2FMakefile+openssl&type=code

which had 2 results, both of which use a custom include path for OpenSSL, so this is a step forward.

**Pull request merged**
